apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  postgres-user: cG9zdGdyZXM=  # base64 encoded version of the username "postgres"
  postgres-password: YWp1amFjb2I=  # base64 encoded version of the password "ajujacob"
  postgres-db: c21hcnRzdG9yZV9lY29tbWVyY2VfcHJvamVjdA==  # base64 encoded version of the database name "smartstore_ecommerce_project"
