apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartstore-webapp-deployment
  labels:
    app: smartstore-webapp
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: smartstore-webapp
  template:
    metadata:
      labels:
        app: smartstore-webapp
    spec:
      containers:
      - name: web-ecommerce-app
        image: ajujacob/smarstore-ecommerce-api:0.0.1.RELEASE
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: DB_PORT
          value: "5432"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
