apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  mongo-user: bW9uZ291c2Vy            # username encoding done via https://www.base64encode.org/,, this bW9uZ291c2Vy is base64 encoded version of the username "mongouser",, we can use any user name,, mongo-user is just a variable name
  mongo-password: bW9uZ29wYXNzd29yZA==    # password encoding done via https://www.base64encode.org/,, this bW9uZ291c2Vy is base64 encoded version of the password "mongopassword",, we can use any password,, mongo-password is just a variable name